#pragma once

#include "hardware/pio.h"
#include <stdbool.h>
#include <stdint.h>

// Minimal WS2812 (NeoPixel) driver for RP2040 using PIO.
// - Uses the `ws2812.pio` program (header generated by CMake)
// - Writes pixels in GRB order (standard WS2812)

typedef struct neopixel_ws2812 {
  PIO pio;
  uint sm;
  uint pin;
  bool is_rgbw;
} neopixel_ws2812_t;

// Initialize a WS2812 output on `pin` at `freq_hz` (normally 800000).
// Claims an unused state machine on the provided PIO block.
void neopixel_ws2812_init(neopixel_ws2812_t *np, PIO pio, uint pin,
                          float freq_hz, bool is_rgbw);

// Set the first pixel to an RGB value (0-255 per channel).
void neopixel_ws2812_put_rgb(neopixel_ws2812_t *np, uint8_t r, uint8_t g,
                             uint8_t b);

// Set the first pixel to a raw GRB value (24-bit).
void neopixel_ws2812_put_grb_u32(neopixel_ws2812_t *np, uint32_t grb);
